---
title: "Class14"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Asthma SNPs in MXL population

Read file from Ensembl

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
sum(mxl$Genotype..forward.strand.=="G|G")
```

Percent Values

```{r}
table(mxl$Genotype..forward.strand.)/nrow(mxl)*100
```

##RNA-Seq

Fastq quality scores

Q. Does the first sequence have good quality?
```{r}
q <- "DDDDCDEDCDDDDBBDDDCC@"
library(seqinr)
library(gtools)
asc(s2c(q))-33
```

## Population scale analysis

Does the genotype for rs9067378 influence expression of the improtant asthma linked genes we found?

```{r}
geno <- read.table("rs8067378_ENSG00000172057.6.txt")
head(geno)
```

```{r}
table(geno$geno)
```

```{r}
inds <- geno$geno=="G/G"
summary(geno$exp[inds])
```

```{r}
inds <- geno$geno=="A/A"
summary(geno$exp[inds])
```

```{r}
inds <- geno$geno=="A/G"
summary(geno$exp[inds])
```

```{r}
boxplot(exp~geno, geno)
```





